### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by inaja** [mmeimaris/EvoGen#1]
Running EvoGen without any modification and with the parameters described gives a java.lang.IllegalArgumentException:
Details:
Exception in thread "main" java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Random.java:388)
	at org.imis.generator.EvoGenerator._getRandomFromRange(EvoGenerator.java:2638)
	at org.imis.generator.EvoGenerator._AssignGraduateCourse(EvoGenerator.java:1611)
	at org.imis.generator.EvoGenerator._generateAFaculty_a(EvoGenerator.java:1533)
	at org.imis.generator.EvoGenerator._generateALecturer(EvoGenerator.java:1760)
	at org.imis.generator.EvoGenerator._generateASection(EvoGenerator.java:1389)
	at org.imis.generator.EvoGenerator._generate(EvoGenerator.java:1090)
	at org.imis.generator.EvoGenerator.start(EvoGenerator.java:862)
	at org.imis.generator.EvoGenerator.main(EvoGenerator.java:680)

I have done the following edits:
Changed _getRandomFromRange from:
`private int _getRandomFromRange(int min, int max) {`
`   return min + random_.nextInt(max - min + 1);`
` }`
to 
`private int _getRandomFromRange(int min, int max) {`
`	  if (min < 0 || max < 0) {`
`	    throw new IllegalArgumentException("You passed a negative bound");`
`      }`
`      else if (max < min) {`
`       System.out.println("--You passed a max which less than the min, so max will be increased by 1");`
`        return min;`
 `     }`
`    return min + random_.nextInt(max - min + 1);`
`  }`
and in `_AssignGraduateCourse`, I changed 
`int pos = _getRandomFromRange(0, remainingGradCourses_.size() - 1);`
`pos = 0; //fetch courses in sequence`
to
`int pos;`
`    if (remainingGradCourses_.size() > 1) {`
`      pos = _getRandomFromRange (0, remainingGradCourses_.size() - 1);`
`    }`
`      pos = 0; //fetch courses in sequence`

I have a new error now:
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at org.imis.generator.EvoGenerator._AssignGraduateCourse(EvoGenerator.java:1617)
	at org.imis.generator.EvoGenerator._generateAFaculty_a(EvoGenerator.java:1533)
	at org.imis.generator.EvoGenerator._generateALecturer(EvoGenerator.java:1760)
	at org.imis.generator.EvoGenerator._generateASection(EvoGenerator.java:1389)
	at org.imis.generator.EvoGenerator._generate(EvoGenerator.java:1090)
	at org.imis.generator.EvoGenerator.start(EvoGenerator.java:862)
	at org.imis.generator.EvoGenerator.main(EvoGenerator.java:680)

So, in `_AssignGraduateCourse`, I made the further changes from:
    `CourseInfo course = new CourseInfo();`
    `course.indexInFaculty = indexInFaculty;`
    `course.globalIndex = ( (Integer) remainingGradCourses_.get(pos)).intValue();`
    `gradCourses_.add(course);	`							 
    `remainingGradCourses_.remove(pos);`
    `return course.globalIndex;`
to
`if(!remainingGradCourses_.isEmpty()) {`
    `CourseInfo course = new CourseInfo();`
     `course.indexInFaculty = indexInFaculty;`
     `course.globalIndex = ((Integer) remainingGradCourses_.get(pos)).intValue();`
     `gradCourses_.add(course);`
     `remainingGradCourses_.remove(pos);`
     `return course.globalIndex;`
`  }`
`  else`
`    return 0;`

That seemed to do the trick until I encountered the same list of error and did the same modifications to `_AssignWebCourse`, `_AssignCourse`, 
then, it ran ok until I got an error on the line `characteristicSetMap.put(previous.asNode(), cs);`:
Exception in thread "main" java.lang.NullPointerException
	at org.imis.generator.EvoGenerator.main(EvoGenerator.java:759) 
so I surrounded it with if not empty to become:
 `if (!properties.isEmpty()) {`
 `   characteristicSetMap.put(previous.asNode(), cs);`
 `}`

**Comment by amitabhpriyadarshi** [comment]
@inaja does this work for you at the end? if so please let me know asap.
@mmeimaris can you help me out i am encountering the same errors.
